/**
 * List of official languages in English
 * This list includes commonly recognized official languages used in international contexts
 */
export const OFFICIAL_LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Dutch',
  'Russian',
  'Chinese (Mandarin)',
  'Japanese',
  'Korean',
  'Arabic',
  'Hindi',
  'Turkish',
  'Polish',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Greek',
  'Czech',
  'Hungarian',
  'Romanian',
  'Bulgarian',
  'Croatian',
  'Serbian',
  'Slovak',
  'Slovenian',
  'Estonian',
  'Latvian',
  'Lithuanian',
  'Ukrainian',
  'Belarusian',
  'Macedonian',
  'Albanian',
  'Maltese',
  'Icelandic',
  'Irish',
  'Welsh',
  'Catalan',
  'Basque',
  'Galician',
  'Hebrew',
  'Persian',
  'Urdu',
  'Bengali',
  'Tamil',
  'Thai',
  'Vietnamese',
  'Indonesian',
  'Malay',
  'Tagalog',
  'Swahili',
  'Afrikaans',
  'Amharic',
  'Georgian',
  'Armenian',
  'Azerbaijani',
  'Kazakh',
  'Mongolian',
  'Nepali',
  'Sinhala',
  'Burmese',
  'Khmer',
  'Lao',
].sort(); // Sort alphabetically for easier selection

export function isValidOfficialLanguage(language: string): boolean {
  return OFFICIAL_LANGUAGES.includes(language);
}

