export const SPORTS_LIST = [
  'canoeing',
  'canyoning',
  'catamaran',
  'e-foil',
  'flyboarding',
  'hydrofoil kite surfing',
  'hydrofoil surfing',
  'jet-skiing',
  'kayaking',
  'kitesurfing',
  'parasailing',
  'rafting',
  'sailing',
  'scuba-diving',
  'snorkeling',
  'Paddle boarding (SUP)',
  'surfing',
  'wakeboarding',
  'water-skiing',
  'windsurfing',
  'wing foiling',
  'yachting',
  'Other (see job description)',
];

